#pragma once

#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN_DARK 0x02
#define FOREGROUND_CYAN_DARK 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA_DARK 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_GRAY_LIGHT 0x07
#define FOREGROUND_GRAY_DARK 0x08
#define FOREGROUND_PURPLE 0x09
#define FOREGROUND_GREEN 0x0a
#define FOREGROUND_CYAN 0x0b
#define FOREGROUND_ORANGE 0x0c
#define FOREGROUND_MAGENTA 0x0d
#define FOREGROUND_YELLOW 0x0e
#define FOREGROUND_WHITE 0x0f

#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN_DARK 0x20
#define BACKGROUND_CYAN_DARK 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA_DARK 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_GRAY_LIGHT 0x70
#define BACKGROUND_GRAY_DARK 0x80
#define BACKGROUND_PURPLE 0x90
#define BACKGROUND_GREEN 0xa0
#define BACKGROUND_CYAN 0xb0
#define BACKGROUND_ORANGE 0xc0
#define BACKGROUND_MAGENTA 0xd0
#define BACKGROUND_YELLOW 0xe0
#define BACKGROUND_WHITE 0xf0